# Generated by Django 4.2.24 on 2025-09-24 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Climat',
            fields=[
                ('idClimat', models.AutoField(primary_key=True, serialize=False)),
                ('nomClimat', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('idMessage', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=10000)),
                ('idClimat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climats_messages', to='campusZen.climat')),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('idPers', models.AutoField(primary_key=True, serialize=False)),
                ('emailPers', models.CharField(max_length=255)),
                ('passwordPers', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=50)),
                ('lastConnection', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Professionnel',
            fields=[
                ('idPro', models.AutoField(primary_key=True, serialize=False)),
                ('nomPro', models.CharField(max_length=255)),
                ('prenomPro', models.CharField(max_length=255)),
                ('fonctionPro', models.CharField(max_length=255)),
                ('emailPro', models.CharField(max_length=255)),
                ('telephonePro', models.CharField(max_length=20)),
                ('adressePro', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('idQuestion', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('idR', models.AutoField(primary_key=True, serialize=False)),
                ('typeR', models.CharField(max_length=255)),
                ('titreR', models.CharField(max_length=255)),
                ('descriptionR', models.CharField(max_length=500)),
                ('lienR', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateStatut', models.DateTimeField(auto_now=True)),
                ('idClimat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climats_statuts', to='campusZen.climat')),
                ('idPers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnes_statuts', to='campusZen.personne')),
            ],
        ),
        migrations.CreateModel(
            name='Recu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateMessage', models.DateTimeField(auto_now=True)),
                ('idMessage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus', to='campusZen.message')),
                ('idPers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnes_recus', to='campusZen.personne')),
            ],
        ),
        migrations.CreateModel(
            name='ConsulteRessource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnes_consultes', to='campusZen.personne')),
                ('idR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ressources_consultes', to='campusZen.ressource')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultePro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnes_consultesPro', to='campusZen.personne')),
                ('idPro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professionnels_consultes', to='campusZen.professionnel')),
            ],
        ),
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('idAvis', models.AutoField(primary_key=True, serialize=False)),
                ('nbEtoile', models.IntegerField()),
                ('messageAvis', models.CharField(max_length=255)),
                ('dateAvis', models.DateTimeField(auto_now=True)),
                ('idPers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnes_avis', to='campusZen.personne')),
            ],
        ),
    ]
