# Generated by Django 5.2.6 on 2025-09-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusZen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='emailPers',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='personne',
            name='role',
            field=models.CharField(choices=[('étudiant', 'Étudiant'), ('admin', 'Admin')], default='étudiant', max_length=50),
        ),
        migrations.AlterField(
            model_name='professionnel',
            name='emailPro',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
