# Generated by Django 4.2.24 on 2025-10-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusZen', '0002_alter_personne_emailpers_alter_personne_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='emailPers',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
