# Generated by Django 4.2.24 on 2025-10-15 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("campusZen", "0003_alter_personne_emailpers"),
    ]

    operations = [
        migrations.CreateModel(
            name="Questionnaire",
            fields=[
                (
                    "idQuestionnaire",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("nomQuestionnaire", models.CharField(max_length=255)),
                ("descriptionQuestionnaire", models.CharField(max_length=500)),
            ],
        ),
        migrations.RenameField(
            model_name="question",
            old_name="question",
            new_name="textQuestion",
        ),
        migrations.CreateModel(
            name="Seuil",
            fields=[
                (
                    "idQuestionnaire",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("minScore", models.IntegerField()),
                ("maxScore", models.IntegerField()),
                ("descriptionSeuil", models.CharField(max_length=255)),
                (
                    "idClimat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="climats_seuils",
                        to="campusZen.climat",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("textReponse", models.CharField(max_length=255)),
                ("score", models.IntegerField()),
                ("echelle", models.IntegerField()),
                (
                    "questionId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions_reponses",
                        to="campusZen.question",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="question",
            name="questionnaireId",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questionnaires_questions",
                to="campusZen.questionnaire",
            ),
        ),
    ]
