# Generated by Django 4.2.24 on 2025-11-12 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "campusZen",
            "0004_questionnaire_rename_question_question_textquestion_and_more",
        ),
    ]

    operations = [
            # migrations.RenameField(
            #     model_name="question",
            #     old_name="textQuestion",
            #     new_name="intituleQuestion",
            # ),
        # migrations.RenameField(
        #     model_name="reponse",
        #     old_name="textReponse",
        #     new_name="texte",
        # ),
        migrations.RenameField(
            model_name="seuil",
            old_name="descriptionSeuil",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="seuil",
            old_name="idQuestionnaire",
            new_name="idSeuil",
        ),
        # migrations.RemoveField(
        #     model_name="reponse",
        #     name="echelle",
        # ),
        migrations.RemoveField(
            model_name="reponse",
            name="id",
        ),
        migrations.RemoveField(
            model_name="reponse",
            name="questionId",
        ),
        migrations.RemoveField(
            model_name="seuil",
            name="idClimat",
        ),
        migrations.RemoveField(
            model_name="statut",
            name="idClimat",
        ),
        migrations.RemoveField(
            model_name="statut",
            name="idPers",
        ),
        migrations.AddField(
            model_name="question",
            name="poids",
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name="reponse",
            name="idReponse",
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name="reponse",
            name="question",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reponses",
                to="campusZen.question",
            ),
        ),
        migrations.AddField(
            model_name="seuil",
            name="climat",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seuils",
                to="campusZen.climat",
            ),
        ),
        migrations.AddField(
            model_name="seuil",
            name="questionnaire",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seuils",
                to="campusZen.questionnaire",
            ),
        ),
        migrations.AddField(
            model_name="statut",
            name="climat",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="statuts",
                to="campusZen.climat",
            ),
        ),
        migrations.AddField(
            model_name="statut",
            name="personne",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="statuts",
                to="campusZen.personne",
            ),
        ),
        migrations.AddField(
            model_name="statut",
            name="scoreTotal",
            field=models.FloatField(default=0.0),
        ),
    ]
