# Generated by Django 4.2.24 on 2025-11-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusZen', '0005_remove_personne_passwordpers_personne_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionnel',
            name='lat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professionnel',
            name='long',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
