# Generated by Django 4.2.24 on 2025-11-18 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campusZen', '0005_rename_textquestion_question_intitulequestion_and_more'),
        ('campusZen', '0006_professionnel_lat_professionnel_long'),
    ]

    operations = [
    ]
