# Generated by Django 4.2.24 on 2025-11-18 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campusZen', '0007_merge_20251118_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='textQuestion',
            new_name='intituleQuestion',
        ),
        migrations.RenameField(
            model_name='statut',
            old_name='climat',
            new_name='idClimat',
        ),
        migrations.RenameField(
            model_name='statut',
            old_name='personne',
            new_name='idPers',
        ),
    ]
