# Generated by Django 4.2.24 on 2025-11-26 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campusZen', '0007_merge_20251119_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='textQuestion',
        ),
        migrations.RemoveField(
            model_name='reponse',
            name='echelle',
        ),
        migrations.RemoveField(
            model_name='reponse',
            name='textReponse',
        ),
        migrations.AddField(
            model_name='question',
            name='intituleQuestion',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reponse',
            name='texte',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reponse',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='campusZen.question'),
            preserve_default=False,
        ),
    ]
