# Generated by Django 4.2.24 on 2025-12-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusZen', '0008_remove_question_textquestion_remove_reponse_echelle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ressource',
            name='typeR',
            field=models.CharField(choices=[('article', 'Article'), ('video', 'Vidéo'), ('podcast', 'Podcast'), ('livre', 'Livre'), ('site_web', 'Site Web'), ('documentaire', 'Documentaire'), ('film', 'Film'), ('formation', 'Formation'), ('autre', 'Autre')], max_length=255),
        ),
    ]
