# Generated by Django 4.2.24 on 2026-01-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusZen', '0009_alter_ressource_typer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='typeQuestion',
            field=models.CharField(choices=[('choix_multiple', 'Choix multiple'), ('choix_unique', 'Choix unique'), ('likert', 'Likert'), ('slider', 'Slider')], default='choix_multiple', max_length=50),
        ),
    ]
