# Generated by Django 4.2.24 on 2026-01-21 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campusZen', '0009_alter_ressource_typer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='typeQuestion',
            field=models.CharField(choices=[('choix_multiple', 'Choix multiple'), ('choix_unique', 'Choix unique'), ('likert', 'Likert'), ('slider', 'Slider')], default='choix_multiple', max_length=50),
        ),
        migrations.AddField(
            model_name='ressource',
            name='climat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ressources', to='campusZen.climat'),
        ),
    ]
