# Generated by Django 6.0.1 on 2026-01-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusZen', '0010_question_typequestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='typeQuestion',
            field=models.CharField(choices=[('likert', 'Likert'), ('slider', 'Slider'), ('smileys', 'Smiley')], default='likert', max_length=50),
        ),
    ]
