# Generated by Django 6.0.1 on 2026-02-04 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campusZen', '0010_question_typequestion_ressource_climat'),
        ('campusZen', '0012_alter_question_typequestion'),
    ]

    operations = [
    ]
