# Generated by Django 6.0.1 on 2026-02-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusZen', '0013_merge_20260204_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='typeQuestion',
            field=models.CharField(choices=[('likert', 'Likert'), ('slider', 'Slider'), ('smiley', 'Smiley')], default='likert', max_length=50),
        ),
    ]
