version: '3.8'

services:
  # Backend Django
  django-api:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://user:password@postgres:5432/myapp
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
    command: python manage.py runserver 0.0.0.0:8000

  # Base de données
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Frontend React Native (pour le développement)
  expo-dev:
    build: ./frontend
    ports:
      - "19000:19000"  # Metro bundler
      - "19001:19001"  # Expo dev tools
      - "19002:19002"  # Expo dev server
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0

volumes:
  postgres_data: